### ISSUE TITLE
Error Recovery 

### ISSUE THREAD

**Issue by cromemcos** [dwildie/cromix-fs#5]
Not sure how practical a request this is ...

I notice that if using the -x to extract files on a partially faulty archive the program gives up on the first error.  Here is an example

goto the cromemcos github and find disk326 in IMD format

https://github.com/cromemcos/m/blob/main/cromemco/code/disks/326FLASH.IMD

you program is able to fully list , but on extraction ...

       61 F  1 rewa re-- re--     0     1 1984-09-01 10:17:12 /flashram/page1.bin
       68 F  1 rewa re-- re--     0     1 1984-09-01 11:25:33 /flashram/xxutest.bin
       40 F  1 rewa re-- re--     0     1 1984-09-01 12:03:03 /flashram/xxu3.o68
       61 F  1 rewa re-- re--     0     1 1984-09-01 12:03:25 /flashram/xxu3.bin
       61 F  1 rewa re-- re--     0     1 1984-09-01 10:18:27 /flashram/look.bin
      235 F  1 r-wa r--- r---     0     1 1984-09-01 12:03:25 /flashram/xxu3.map
      240 F  1 rewa re-- re--     0     1 1984-09-01 08:55:02 /flashram/mport.bin
      506 F  1 rewa re-- re--     0     1 1984-09-01 11:49:17 /flashram/xxu2.asm
      250 F  1 rewa re-- re--     0     1 1984-09-01 08:55:22 /flashram/memb1.bin
    22997 F  1 rewa re-- re--     0     1 2036-02-06 10:00:08 /flashram/sectors.bad
Exception in thread "main" au.wildie.m68k.cromixfs.disk.imd.ImageException: Cannot find cylinder 55, head 1, sector 5
        at au.wildie.m68k.cromixfs.disk.imd.IMDImage.lambda$getSector$10(IMDImage.java:269)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at au.wildie.m68k.cromixfs.disk.imd.IMDImage.getSector(IMDImage.java:269)
        at au.wildie.m68k.cromixfs.disk.floppy.cromix.CromixFloppyDisk.getBlock(CromixFloppyDisk.java:81)
        at au.wildie.m68k.cromixfs.fs.CromixFileSystem.extractFile(CromixFileSystem.java:170)
        at au.wildie.m68k.cromixfs.fs.CromixFileSystem.readDirectory(CromixFileSystem.java:153)
        at au.wildie.m68k.cromixfs.fs.CromixFileSystem.readDirectory(CromixFileSystem.java:143)
        at au.wildie.m68k.cromixfs.fs.CromixFileSystem.extract(CromixFileSystem.java:86)
        at au.wildie.m68k.App.main(App.java:51)

----

I attached the real IMD by converting to HFE format of an HxC emulator and then read on a physical system ...

./flashram/xxu3.map
./flashram/mport.bin
./flashram/xxu2.asm
./flashram/memb1.bin
CFLOP Preread error, Unit 0, Side 1, Track 55, Sector 6, Not Found
Disk I/O error
./flashram/memb8.bin
./flashram/xxu2.bin
./flashram/memw1.bin
./flashram/memw4.bin
./sdi2
./sdi2/bigzoom.bin
./sdi2/bimem.bin
./sdi2/cmap.bin
./sdi2/diag2.bin
./sdi2/dimem.bin

SO the real system continues the read of the whole directory and I think I lost only memb1.bin  but was able to salvage all other files on the diskette.

If the program could be made to continue this would be more effective.

**Comment by dwildie** [comment]
Has been addressed in release 1.3
